version: "3.4"
services:
  proxy:
    build:
      context: ../
      target: caddy
      dockerfile: ./build/Dockerfile
    ports:
      - "9090:9090"
    command: "./caddy run --config config.json"
    networks:
      - demo

  protected:
    build:
      context: ../
      target: protected
      dockerfile: ./build/Dockerfile
    command: "./protected"
    expose:
      - "8080"
    networks:
      - demo

  oauth:
    image: quay.io/pusher/oauth2_proxy:v4.0.0
    environment:
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=:7777
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:9090/oauth2/callback
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_COOKIE_DOMAIN=localhost
      - OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_COOKIE_SECRET
      - OAUTH2_PROXY_CLIENT_SECRET
    expose:
      - "7777"
    networks:
      - demo

networks:
  demo:
